config/routes.rb
Mjnews::Application.routes.draw do
   root 'stories#index' #eventually will be stories#index


  resources :stories do
    member do
      get  :followers
      post :vote
      get :microposts

    end
  end

  resources :users do
    member do
      get :following
      get :microposts
    end
  end




  get 'stories/index'
  get "static_pages/home"
  get "static_pages/about"
  get "users/new"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :stories, only: [:create, :destroy]
  resources :microposts


  match '/stories', to: 'stories#index', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match 'post', to: 'stories#new' ,via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/new', to: 'stories#newstories', via: 'get'





  # You can have the root of your site routed with "root"


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :microposts
  #default_scope -> { order('created_at DESC') }

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 140, minimum: 3}
  validates :url, presence: true, uniqueness: {case_sensitive: false}
end

app/controllers/stories_controller.rb
require 'will_paginate/array'

class StoriesController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]


  def new
    @story = Story.new
  end

  def index
    @stories_hash = {}                  
    @stories = Story.all

    #Place stories in hash. Sort Hash, Place sorted hash into an array for easy display
    @stories.each do |story|
      #store this shit with ranking
      time_since_post = TimeDifference.between(Time.now, story.created_at).in_hours
      ranking = ((story.points.to_i - 1) / (time_since_post + 2)**1.5)
       a = story.id
      @stories_hash[a] = ranking
    end 
    @sorted_stories = @stories_hash.sort_by {|story, ranking| ranking}  #hash sort by ranking
    @display_stories = []
    counter = @sorted_stories.count

    @stories_hash.each {| storyid, rank |
      st = Story.find_by_id(storyid)
      st.rank = rank
      st.save
} 
  @thesort = Story.order(:rank)
  @thesort = @thesort.reverse

  @thesort = @thesort.paginate(page: params[:page], per_page: 20 )
  
     
  end

  def create
    @story = current_user.stories.build(story_params)
    current_user.relationships.create(followed_id: @story.id)
    @story.points = 1
    if @story.save
      flash[:success] = "Link Posted!"
      redirect_to root_url
    else
      render 'stories'
    end
  end

  def followers
    @title = "Voters"
    @story = Story.find(params[:id])
    @users = @story.followers_users.paginate(page: params[:page])
  end

  def show
    @story = Story.find(params[:id])
    @micropost = Micropost.new
    @microposts = Micropost.find_by story_id: @story.id
  end

  def vote
    if current_user == nil
      flash[:notice] = "Please Sign In To Vote"
      redirect_to signin_path
    else
      session[:return_to] ||= request.referer
      @story = Story.find(params[:id])
      @story.points = @story.points.to_i + 1
      @story.save
      current_user.relationships.create(followed_id: @story.id)
      redirect_to session.delete(:return_to)
    end

  end

  def newstories
    @stories = Story.all.reverse

  end


  private

  def story_params
    params.require(:story).permit(:title, :url)
  end


end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_follow.html.erb
        <div class="col-sm-1" class="follow_form">
              <%= form_for(current_user.relationships.build(followed_id: story.id), remote: true) do |f| %>
              <%= f.hidden_field :followed_id%>
                   
              <%= f.submit "^",class: "btn btn-primary btn-sm" %>
        </div>
              <% end %>
  Points: <%= story.points %>14<span class="title"><%= story.title %></span>
  <span class="url"><%= story.url %> </span>
  <span class="timestamp">
  Posted <%= time_ago_in_words(story.created_at)%> ago.
  </span>
</li>
</ul>

app/views/stories/_story.html.erb
 
<span class="points">Points:<%= story.points %> </span>
 <span class= "posted_at ">Posted <%= time_ago_in_words(story.created_at)%> ago.</span>
<span class="posted_by "> posted by: <%= story.user.name %></span>

app/views/stories/_unfollow.html.erb
<div class="col-sm-1" class="follow_form">Voted On</div>
       <div class="col-5">

  Points: <%= story.points %>14<span class="title"><%= story.title %></span>
  <span class="url"><%= story.url %> </span>
  <span class="timestamp">
  Posted <%= time_ago_in_words(story.created_at)%> ago.
  </span>
</div>
</li>
</ul>

app/views/stories/index.html.erb
<ol start="1" class="col-sm-10">
  <% @thesort.each do |story| %>
    <li class="stories">
    <div class="vote">
           <%= link_to vote_story_path(story),id:"vote_button", method: :post do %>
           <span class="glyphicon glyphicon-chevron-up"></span>
           <% end %>
      
    </div>
      
     <div class="story_display"> 

    <% clean_url = Domainatrix.parse(story.url)%>
    <span class="title"> <%= link_to story.title, story.url %> </span>(<%= "#{clean_url.domain}.#{clean_url.public_suffix}"%>) <br />    
    
    <span class="points">Points:<%= story.points %> </span>
    
    
    <span class="posted_by "> posted by <%= link_to story.user.name, story.user %></span> 
    <span class="posted_at "><%= time_ago_in_words(story.created_at)%> ago.</span> |
    <span class="num_comments"><%= link_to "comments #{story.microposts.count}", story %>  </span>
  </div>
  </li>
    <%end%>
</ol>
<%= will_paginate @thesort %>

app/views/stories/new.html.erb
<legend>New Story</legend>
<div class="col-sm-5">
<%= form_for(@story) do |f| %>

    
            <%= f.label :title %>
            <%= f.text_field :title %>
      
    
     
        <%= f.label :url %>
        <%= f.text_field :url %>
        
        <%= f.submit "Submit", class: "btn btn-primary" %>

<% end %>
</div>

app/views/stories/newstories.html.erb
<% @stories.each do |story| %>
	

	<li class="stories">
  	

    <div class="vote">
           

           <%= link_to vote_story_path(story),id:"vote_button", method: :post do %>
           <span class="glyphicon glyphicon-chevron-up"></span>
           <% end %>
          
      
    </div>
      
     <div class="story_display"> 

    <% clean_url = Domainatrix.parse(story.url)%>
    <span class="title"> <%= link_to story.title, story.url %> </span>(<%= "#{clean_url.domain}.#{clean_url.public_suffix}"%>) <br />    
    
    <span class="points">Points:<%= story.points %> </span>
    
    
    <span class="posted_by "> posted by <%= link_to story.user.name, story.user %></span> 
    <span class="posted_at "><%= time_ago_in_words(story.created_at)%> ago.</span> |
    <span class="num_comments"><%= link_to "comments #{story.microposts.count}", story %>  </span>
  </div>
  </li>
    <%end%>
</ol>

app/views/stories/show.html.erb
<% provide(:title, @story.title) %>


    
    <% clean_url = Domainatrix.parse(@story.url)%>
    <span class="title"> <%= link_to @story.title, @story.url %> </span>(<%= "#{clean_url.domain}.#{clean_url.public_suffix}"%>) <br />    
    
    <span class="points">Points:<%= @story.points %> </span>
    
    
    <span class="posted_by "> posted by <%= link_to @story.user.name, @story.user %></span> 
    <span class="posted_at "><%= time_ago_in_words(@story.created_at)%> ago.</span> |
    <span class="num_comments">comments <%= @story.microposts.count %>  
      
   
    <br /><br />
    <%= render 'microposts/form' %>
    
    
    <h3>Comments <%= @story.microposts.count %></h3>
    
    <%= nested_microposts @story.microposts.arrange(order: :created_at) %>
    
    
  </div>
  