config/routes.rb
Mjnews::Application.routes.draw do
   root 'stories#index' #eventually will be stories#index


  resources :stories do
    member do
      get  :followers
      post :vote
      get :microposts

    end
  end

  resources :users do
    member do
      get :following
      get :microposts
    end
  end




  get 'stories/index'
  get "static_pages/home"
  get "static_pages/about"
  get "users/new"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :stories, only: [:create, :destroy]
  resources :microposts


  match '/stories', to: 'stories#index', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match 'post', to: 'stories#new' ,via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/new', to: 'stories#newstories', via: 'get'





  # You can have the root of your site routed with "root"


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: :true
  validates :story_id, presence: :true
  validates :content, presence: true
  has_ancestry

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
before_action :signed_in_user, only: [:create, :destroy]

  def new
    @micropost = Micropost.new(parent_id: params[:parent_id])
  end

  def index

  end

  def create
    @micropost = current_user.microposts.build(micropost_params)

    @micropost.story_id = @micropost.root.story_id
    
    if @micropost.save
        flash[:success] = "Will BreakSoon"
    end
    redirect_to root_url
  end




  def destroy
  end

  private

  def micropost_params
    params.require(:micropost).permit(:user_id, :comment_id,:story_id, :content, :parent_id)
  end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def nested_microposts(microposts)
    microposts.map do |post, sub_post|
      render(post) + content_tag(:div, nested_microposts(sub_post), class: "nested_microposts")
    end.join.html_safe
  end
end

app/views/microposts/_form.html.erb
  <%= form_for(@micropost) do |f| %>

    <%= f.text_area :content, placeholder: "Marijuana News. It's All In The Comments" %>
    <%= f.hidden_field :story_id, value: @story.id %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :comment_id, value: "TBD" %>
    <%= f.hidden_field :parent_id %>
    
  <%= f.submit "Submit", class: "submit btn  btn-primary" %>
<% end %>

app/views/microposts/_micropost.html.erb
<li>
  <%= micropost.content %>
 
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
 
  Posted by: <%= link_to micropost.user.name, micropost.user %>
<%= link_to "reply", new_micropost_path(parent_id: micropost) %>
</li>

app/views/microposts/new.html.erb
<p><%= @micropost.parent.content if @micropost.parent %></p>
  <%= form_for(@micropost) do |f| %>

    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    <%= f.hidden_field :story_id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :comment_id, value: "TBD" %>
    <%= f.hidden_field :parent_id %>

  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>