config/routes.rb
Mjnews::Application.routes.draw do
   root 'stories#index' #eventually will be stories#index


  resources :stories do
    member do
      get  :followers
      post :vote
      get :microposts

    end
  end

  resources :users do
    member do
      get :following
      get :microposts
    end
  end




  get 'stories/index'
  get "static_pages/home"
  get "static_pages/about"
  get "users/new"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :stories, only: [:create, :destroy]
  resources :microposts


  match '/stories', to: 'stories#index', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match 'post', to: 'stories#new' ,via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/new', to: 'stories#newstories', via: 'get'





  # You can have the root of your site routed with "root"


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<div class='col-lg-10'>
<footer class="footer">
  <small>
    <a href="mjnews.co">Marijuana News</a>
    by David Midler
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_url %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to root_url %></li>
    </ul>
  </nav>
</footer>
</div>

app/views/layouts/_header.html.erb
<nav class='navbar navbar-fixed-top navbar'>
  <div class='navbar_header'>

  <a class='navbar-brand' id="logo" href= "/">Marijuana News</a>

      <ul class='nav navbar-nav pull-left' >
      <li><%=link_to "New", 'stories#newstories'%></li>
      <li><%=link_to "Top" , stories_path %> </li>
      <li><%=link_to "Weekly", stories_path %></li>
</ul>



   <div class="navbar-collapse collapse">


          <ul class="drop-down-menu nav navbar-nav pull-right">

          <% if signed_in? %>



 <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%=current_user.name%> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>    
              

               
                <li class="divider"></li>
                <li>
                  <li><%= link_to "#{current_user.name} (Sign out)", signout_path, method: "delete" %></li> 
                 
                </li>
              </ul>
            </li>





           
            
            <li><%= link_to "Post",    post_path, id: 'post-btn'%></li>

      <%else%>

          <li class='post-btn'><%= link_to "Sign in", signin_path %></li>


      <%end%>

</ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_stories.html.erb
<li>
  Points: <%=story.points %><span class="title"><%= story.title %></span>
  <span class="url"><%= story.url %> </span>
  <span class="timestamp">
  Posted <%= time_ago_in_words(story.created_at)%> ago.
  </span>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MJNews</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<div class="container">
<%= render'layouts/header' %>
<%= render partial: "shared/flash_messages", flash: flash %> 
<%= yield %>
</div>
<%= render 'layouts/footer' %>

</body>
</html>